### ISSUE TITLE
Error in monfn(x, Wfdobj) : WFDOBJ is not a single function 

### ISSUE THREAD

**Issue by chenchenzi** [uasolo/FPCA-phonetics-workshop#1]
When I tried the following line of code in exLand.0.R,
reg <- landmarkreg.nocurve(land, nhknots = 8, hlambda=1e-8, wlambda =1e-8),
the error message, " Error in monfn(x, Wfdobj) : WFDOBJ is not a single function " appeared.
It seems that landmarkreg.nocurve() in exercise exLand.R doesn't work either. May I ask how to solve this? Or is there any parameter that I should set beforehand?

**Comment by uasolo** [comment]
Hi,
it appears you are not sourcing header.R before running that script. My
apologies that in exLand0.R I forgot to specify that. But before working on
any of the exemple scripts you need to make sure you have sourced header.R.
The reason is that there are a number of bugs in the old 'fda' package that
I had to fix myself, plus custom functions I wrote.
I hope it helps, apologies for my late reply
Michele

**Comment by chenchenzi** [comment]
Hi Michele,

Thank you for your reply.
I actually sourced header.R, but partially. I'll have a further look. Thank you!
